<?php

namespace Container5CQQWkO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TOlIhRRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TOlIhRR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TOlIhRR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'command' => ['privates', 'App\\Dto\\Command\\CreateTechGuestCommand', 'getCreateTechGuestCommandService', true],
            'techGuest' => ['privates', '.errored..service_locator.TOlIhRR.App\\Entity\\Guest\\TechGuest', NULL, 'Cannot autowire service ".service_locator.TOlIhRR": it needs an instance of "App\\Entity\\Guest\\TechGuest" but this type has been excluded in "config/services.yaml".'],
        ], [
            'command' => 'App\\Dto\\Command\\CreateTechGuestCommand',
            'techGuest' => 'App\\Entity\\Guest\\TechGuest',
        ]);
    }
}
