<?php

namespace Container5CQQWkO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateTechGuestCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Dto\Command\CreateTechGuestCommand' shared autowired service.
     *
     * @return \App\Dto\Command\CreateTechGuestCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Dto/Command/CreateTechGuestCommand.php';

        return $container->privates['App\\Dto\\Command\\CreateTechGuestCommand'] = new \App\Dto\Command\CreateTechGuestCommand();
    }
}
