<?php

namespace Container5CQQWkO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStreamedJsonResponseBuilderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Http\StreamedJsonResponseBuilder' shared autowired service.
     *
     * @return \App\Service\Http\StreamedJsonResponseBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/Http/StreamedJsonResponseBuilder.php';

        return $container->privates['App\\Service\\Http\\StreamedJsonResponseBuilder'] = new \App\Service\Http\StreamedJsonResponseBuilder(($container->privates['serializer'] ?? self::getSerializerService($container)));
    }
}
