<?php

namespace Container5CQQWkO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTechGuest2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.TOlIhRR.App\Entity\Guest\TechGuest' shared service.
     *
     * @return \App\Entity\Guest\TechGuest
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.TOlIhRR": it needs an instance of "App\\Entity\\Guest\\TechGuest" but this type has been excluded in "config/services.yaml".');
    }
}
