<?php

namespace Container5CQQWkO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTechCountryPhoneNumberRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\TechCountryPhoneNumberRepository' shared autowired service.
     *
     * @return \App\Repository\TechCountryPhoneNumberRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/persistence/src/Persistence/ObjectRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/collections/src/Selectable.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/EntityRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/ServiceEntityRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/ServiceEntityRepositoryProxy.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/ServiceEntityRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Repository/Base/BaseRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Repository/TechCountryPhoneNumberRepository.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Repository\\TechCountryPhoneNumberRepository'])) {
            return $container->privates['App\\Repository\\TechCountryPhoneNumberRepository'];
        }

        return $container->privates['App\\Repository\\TechCountryPhoneNumberRepository'] = new \App\Repository\TechCountryPhoneNumberRepository($a, ($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
