<?php

namespace ContainerVpkbdw0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GTS2zw1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GTS2zw1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GTS2zw1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'guest' => ['privates', '.errored..service_locator.GTS2zw1.App\\Entity\\Guest\\TechGuest', NULL, 'Cannot autowire service ".service_locator.GTS2zw1": it needs an instance of "App\\Entity\\Guest\\TechGuest" but this type has been excluded in "config/services.yaml".'],
        ], [
            'guest' => 'App\\Entity\\Guest\\TechGuest',
        ]);
    }
}
