<?php

namespace ContainerVpkbdw0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I6EC1flService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.i6EC1fl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.i6EC1fl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'command' => ['privates', 'App\\Dto\\Command\\CRUDTechGuestCommand', 'getCRUDTechGuestCommandService', true],
            'techGuest' => ['privates', '.errored..service_locator.i6EC1fl.App\\Entity\\Guest\\TechGuest', NULL, 'Cannot autowire service ".service_locator.i6EC1fl": it needs an instance of "App\\Entity\\Guest\\TechGuest" but this type has been excluded in "config/services.yaml".'],
        ], [
            'command' => 'App\\Dto\\Command\\CRUDTechGuestCommand',
            'techGuest' => 'App\\Entity\\Guest\\TechGuest',
        ]);
    }
}
