<?php

namespace ContainerVpkbdw0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTechGuestService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.GTS2zw1.App\Entity\Guest\TechGuest' shared service.
     *
     * @return \App\Entity\Guest\TechGuest
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.GTS2zw1": it needs an instance of "App\\Entity\\Guest\\TechGuest" but this type has been excluded in "config/services.yaml".');
    }
}
