<?php

namespace ContainerZNNjzG8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A3cEoLTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.a3cEoLT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.a3cEoLT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\CreateTechGuestAction::__invoke' => ['privates', '.service_locator.ZHjCRKp', 'get_ServiceLocator_ZHjCRKpService', true],
            'App\\Controller\\DeleteTechGuestAction::__invoke' => ['privates', '.service_locator.GTS2zw1', 'get_ServiceLocator_GTS2zw1Service', true],
            'App\\Controller\\GetTechGuestAction::__invoke' => ['privates', '.service_locator.GTS2zw1', 'get_ServiceLocator_GTS2zw1Service', true],
            'App\\Controller\\UpdateTechGuestAction::__invoke' => ['privates', '.service_locator.i6EC1fl', 'get_ServiceLocator_I6EC1flService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\CreateTechGuestAction:__invoke' => ['privates', '.service_locator.ZHjCRKp', 'get_ServiceLocator_ZHjCRKpService', true],
            'App\\Controller\\CreateTechGuestAction' => ['privates', '.service_locator.ZHjCRKp', 'get_ServiceLocator_ZHjCRKpService', true],
            'App\\Controller\\DeleteTechGuestAction:__invoke' => ['privates', '.service_locator.GTS2zw1', 'get_ServiceLocator_GTS2zw1Service', true],
            'App\\Controller\\DeleteTechGuestAction' => ['privates', '.service_locator.GTS2zw1', 'get_ServiceLocator_GTS2zw1Service', true],
            'App\\Controller\\GetTechGuestAction:__invoke' => ['privates', '.service_locator.GTS2zw1', 'get_ServiceLocator_GTS2zw1Service', true],
            'App\\Controller\\GetTechGuestAction' => ['privates', '.service_locator.GTS2zw1', 'get_ServiceLocator_GTS2zw1Service', true],
            'App\\Controller\\UpdateTechGuestAction:__invoke' => ['privates', '.service_locator.i6EC1fl', 'get_ServiceLocator_I6EC1flService', true],
            'App\\Controller\\UpdateTechGuestAction' => ['privates', '.service_locator.i6EC1fl', 'get_ServiceLocator_I6EC1flService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\CreateTechGuestAction::__invoke' => '?',
            'App\\Controller\\DeleteTechGuestAction::__invoke' => '?',
            'App\\Controller\\GetTechGuestAction::__invoke' => '?',
            'App\\Controller\\UpdateTechGuestAction::__invoke' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CreateTechGuestAction:__invoke' => '?',
            'App\\Controller\\CreateTechGuestAction' => '?',
            'App\\Controller\\DeleteTechGuestAction:__invoke' => '?',
            'App\\Controller\\DeleteTechGuestAction' => '?',
            'App\\Controller\\GetTechGuestAction:__invoke' => '?',
            'App\\Controller\\GetTechGuestAction' => '?',
            'App\\Controller\\UpdateTechGuestAction:__invoke' => '?',
            'App\\Controller\\UpdateTechGuestAction' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
