<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5CQQWkO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5CQQWkO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5CQQWkO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5CQQWkO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5CQQWkO\App_KernelDevDebugContainer([
    'container.build_hash' => '5CQQWkO',
    'container.build_id' => 'd3f1a120',
    'container.build_time' => 1743337559,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container5CQQWkO');
