<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZNNjzG8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZNNjzG8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZNNjzG8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZNNjzG8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZNNjzG8\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZNNjzG8',
    'container.build_id' => '9c71f5cc',
    'container.build_time' => 1743952961,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZNNjzG8');
